/**
 * CRM Template
 * ------------
 * For sales-driven organizations needing customer relationship management.
 * Focus: leads, pipeline, contacts, activities, automation, analytics.
 */
import type { SrgTemplate } from "../types";

export const crmTemplate: SrgTemplate = {
  id: "crm",
  name: "CRM Platform",
  tagline: "Leads, pipeline, automation & customer 360",
  description:
    "For sales-driven organizations needing lead management, pipeline visibility, customer 360, and sales automation.",
  icon: "ContactRound",
  accent: "from-cyan/20 to-cyan/5",
  suggestedGoals: [
    "Increase lead-to-customer conversion by 25%",
    "Automate 60% of follow-up activities",
    "Centralize all customer touchpoints in one view",
    "Build sales forecast with 90% accuracy",
  ],
  sections: [
    {
      id: "crm-scope",
      title: "CRM Scope",
      questions: [
        {
          id: "sales_model",
          type: "select",
          label: "Primary sales model",
          required: true,
          options: [
            { label: "B2B Enterprise", value: "b2b_enterprise" },
            { label: "B2B SMB", value: "b2b_smb" },
            { label: "B2C Retail", value: "b2c_retail" },
            { label: "D2C E-commerce", value: "d2c" },
            { label: "Channel / Partner sales", value: "channel" },
            { label: "Mixed (B2B + B2C)", value: "mixed" },
          ],
        },
        {
          id: "modules_needed",
          type: "multiselect",
          label: "Which CRM modules do you need?",
          required: true,
          options: [
            { label: "Lead Management", value: "leads" },
            { label: "Deal / Opportunity Pipeline", value: "deals" },
            { label: "Contact & Company Database", value: "contacts" },
            { label: "Activity Tracking (calls/meetings)", value: "activities" },
            { label: "Email Integration", value: "email" },
            { label: "Telephony (click-to-call)", value: "telephony" },
            { label: "Quote & Proposal Builder", value: "quotes" },
            { label: "Marketing Automation", value: "marketing" },
            { label: "Customer Support / Tickets", value: "support" },
            { label: "Sales Forecasting", value: "forecast" },
            { label: "Customer 360 View", value: "c360" },
            { label: "Mobile CRM App", value: "mobile" },
            { label: "Reporting & Dashboards", value: "reporting" },
          ],
        },
        {
          id: "sales_reps_count",
          type: "number",
          label: "Number of sales representatives",
          required: true,
          min: 1,
          max: 10000,
        },
        {
          id: "monthly_leads",
          type: "number",
          label: "Average monthly new leads",
          required: true,
          min: 1,
          max: 1000000,
        },
        {
          id: "avg_deal_size",
          type: "text",
          label: "Average deal size (with currency)",
          placeholder: "e.g. ₹2,00,000 / $2,500",
        },
      ],
    },
    {
      id: "crm-pipeline",
      title: "Pipeline & Process",
      questions: [
        {
          id: "pipeline_stages",
          type: "textarea",
          label: "Describe your current sales pipeline stages",
          required: true,
          maxLength: 600,
          placeholder: "e.g. New → Contacted → Qualified → Demo → Proposal → Negotiation → Won/Lost",
        },
        {
          id: "lead_sources",
          type: "multiselect",
          label: "Lead sources to capture",
          required: true,
          options: [
            { label: "Website forms", value: "web_form" },
            { label: "Google Ads / Meta Ads", value: "ads" },
            { label: "LinkedIn", value: "linkedin" },
            { label: "Email campaigns", value: "email" },
            { label: "Cold calls / outbound", value: "outbound" },
            { label: "Events / Trade shows", value: "events" },
            { label: "Referrals", value: "referrals" },
            { label: "WhatsApp / chat", value: "whatsapp" },
            { label: "API from partners", value: "partner_api" },
          ],
        },
        {
          id: "lead_scoring",
          type: "boolean",
          label: "Need automated lead scoring?",
        },
        {
          id: "assignment_rules",
          type: "boolean",
          label: "Need automated lead assignment rules?",
          required: true,
        },
        {
          id: "assignment_logic",
          type: "textarea",
          label: "Describe lead assignment logic",
          showIf: [{ questionId: "assignment_rules", op: "truthy", value: true }],
          maxLength: 600,
          placeholder: "Round-robin, by territory, by deal size, by product line...",
        },
      ],
    },
    {
      id: "crm-automation",
      title: "Automation & Integration",
      questions: [
        {
          id: "automation_needs",
          type: "multiselect",
          label: "Automation workflows needed",
          options: [
            { label: "Auto-respond to new leads", value: "auto_respond" },
            { label: "Follow-up reminders", value: "follow_ups" },
            { label: "Stage-change notifications", value: "stage_notify" },
            { label: "Drip email campaigns", value: "drip" },
            { label: "Win/loss alerts", value: "win_loss" },
            { label: "Idle lead reactivation", value: "idle_reactivate" },
            { label: "Quote approval flow", value: "quote_approval" },
            { label: "Birthday / anniversary wishes", value: "wishes" },
          ],
        },
        {
          id: "external_integrations",
          type: "multiselect",
          label: "External integrations needed",
          options: [
            { label: "Gmail / Outlook", value: "email_client" },
            { label: "WhatsApp Business API", value: "whatsapp" },
            { label: "Twilio / telephony", value: "telephony" },
            { label: "Zoom / Google Meet", value: "video" },
            { label: "Calendly / Cal.com", value: "scheduling" },
            { label: "Mailchimp / SendGrid", value: "email_tool" },
            { label: "Accounting (Tally/QuickBooks)", value: "accounting" },
            { label: "ERP", value: "erp" },
            { label: "E-commerce (Shopify)", value: "ecommerce" },
            { label: "LinkedIn Sales Navigator", value: "linkedin" },
          ],
        },
      ],
    },
    {
      id: "crm-reporting",
      title: "Reporting & AI",
      questions: [
        {
          id: "key_reports",
          type: "multiselect",
          label: "Key reports needed",
          required: true,
          options: [
            { label: "Sales funnel by stage", value: "funnel" },
            { label: "Rep performance leaderboard", value: "rep_perf" },
            { label: "Win/loss analysis", value: "win_loss" },
            { label: "Pipeline coverage", value: "pipeline_coverage" },
            { label: "Lead source ROI", value: "source_roi" },
            { label: "Sales cycle length", value: "cycle_time" },
            { label: "Forecast vs actual", value: "forecast" },
            { label: "Activity metrics (calls/emails)", value: "activity" },
          ],
        },
        {
          id: "ai_features",
          type: "multiselect",
          label: "AI features to include",
          options: [
            { label: "Lead scoring (ML)", value: "lead_scoring" },
            { label: "Deal outcome prediction", value: "deal_predict" },
            { label: "Email / call summary", value: "summary" },
            { label: "Next-best-action suggestions", value: "nba" },
            { label: "Sentiment analysis", value: "sentiment" },
            { label: "Smart forecasting", value: "forecast" },
            { label: "Chatbot for qualification", value: "chatbot" },
          ],
        },
        {
          id: "data_migration_from",
          type: "text",
          label: "Current CRM to migrate from (if any)",
          placeholder: "e.g. Salesforce, HubSpot, Zoho, spreadsheets, none",
        },
      ],
    },
  ],
  uploadRequirements: [
    {
      category: "documents",
      label: "Sales Process Document",
      required: true,
      description: "Current sales process, stages, and qualification criteria",
      accept: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
      maxSizeMB: 25,
    },
    {
      category: "data",
      label: "Sample Lead / Deal Data (anonymized)",
      description: "CSV/XLSX with sample lead and deal records",
      accept: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/csv"],
      maxSizeMB: 15,
    },
    {
      category: "branding",
      label: "Company Logo & Branding",
      required: true,
      accept: ["image/png", "image/jpeg", "image/svg+xml", "application/zip"],
      maxSizeMB: 25,
    },
    {
      category: "reference",
      label: "Reference CRM UIs",
      description: "Screenshots of Salesforce/HubSpot/Zoho screens you like",
      accept: ["image/png", "image/jpeg", "application/zip"],
      maxSizeMB: 25,
      multiple: true,
    },
    {
      category: "documents",
      label: "Lead Assignment / SLA Rules",
      description: "Documented lead routing and response-time SLAs",
      accept: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
      maxSizeMB: 10,
    },
  ],
  workflowRequirements: [
    {
      flow: "customer",
      label: "Lead to Customer",
      required: true,
      defaultStages: ["Lead Capture", "Auto-assign", "First Contact", "Qualification", "Demo", "Proposal", "Negotiation", "Won"],
    },
    {
      flow: "approval",
      label: "Quote Approval",
      defaultStages: ["Draft Quote", "Manager Review", "Discount Approve", "Send to Customer", "Accept/Reject"],
    },
    {
      flow: "verification",
      label: "Lead Verification",
      defaultStages: ["Form Submit", "Email Verify", "Phone Verify", "Qualify", "Assign Rep"],
    },
    {
      flow: "payment",
      label: "Deal to Payment",
      defaultStages: ["Won", "Contract", "Invoice", "Payment", "Onboard"],
    },
    {
      flow: "reporting",
      label: "Sales Reporting",
      required: true,
      defaultStages: ["Daily Activity Log", "Weekly Pipeline Review", "Monthly Forecast", "Quarterly Business Review"],
    },
    {
      flow: "staff",
      label: "Sales Rep Workflow",
      defaultStages: ["Check-in", "Daily Plan", "Calls/Meetings", "Update CRM", "EOD Report"],
    },
  ],
};
