/**
 * ERP Template
 * ------------
 * For enterprises needing a full ERP backbone.
 * Focus: finance, inventory, HR, procurement, sales, manufacturing.
 */
import type { SrgTemplate } from "../types";

export const erpTemplate: SrgTemplate = {
  id: "erp",
  name: "ERP System",
  tagline: "Finance, inventory, HR & operations unified",
  description:
    "For enterprises replacing legacy systems with a unified ERP — finance, inventory, HR, procurement, sales, and operations.",
  icon: "Boxes",
  accent: "from-cyan/25 to-cyan/5",
  suggestedGoals: [
    "Replace 5+ legacy systems with one unified ERP",
    "Achieve real-time inventory visibility across warehouses",
    "Automate 80% of purchase order workflows",
    "Reduce month-end close from 10 days to 3",
  ],
  sections: [
    {
      id: "erp-scope",
      title: "ERP Scope",
      questions: [
        {
          id: "modules_needed",
          type: "multiselect",
          label: "Which ERP modules do you need?",
          required: true,
          options: [
            { label: "Finance & Accounting", value: "finance" },
            { label: "Inventory & Warehouses", value: "inventory" },
            { label: "Procurement / Purchase", value: "procurement" },
            { label: "Sales & CRM", value: "sales" },
            { label: "HR & Payroll", value: "hr" },
            { label: "Manufacturing / Production", value: "manufacturing" },
            { label: "Supply Chain", value: "supply_chain" },
            { label: "Project Management", value: "projects" },
            { label: "Asset Management", value: "assets" },
            { label: "Quality Control", value: "quality" },
            { label: "Customer Portal", value: "customer_portal" },
            { label: "Vendor Portal", value: "vendor_portal" },
            { label: "Employee Self-Service", value: "ess" },
            { label: "BI / Dashboards", value: "bi" },
          ],
        },
        {
          id: "user_count",
          type: "number",
          label: "Expected concurrent users",
          required: true,
          min: 5,
          max: 100000,
        },
        {
          id: "warehouse_count",
          type: "number",
          label: "Number of warehouses / locations",
          min: 1,
          max: 1000,
        },
        {
          id: "entities_count",
          type: "number",
          label: "Number of legal entities (for multi-entity accounting)",
          min: 1,
          max: 500,
        },
        {
          id: "multi_currency",
          type: "boolean",
          label: "Multi-currency operations?",
        },
        {
          id: "multi_company",
          type: "boolean",
          label: "Multi-company / multi-entity consolidation?",
        },
      ],
    },
    {
      id: "erp-integrations",
      title: "Integrations",
      questions: [
        {
          id: "existing_systems",
          type: "multiselect",
          label: "Existing systems to integrate or replace",
          required: true,
          options: [
            { label: "Tally / Busy", value: "tally" },
            { label: "SAP / Oracle", value: "sap_oracle" },
            { label: "Salesforce / Zoho CRM", value: "crm" },
            { label: "Custom legacy software", value: "legacy" },
            { label: "Spreadsheets only", value: "spreadsheets" },
            { label: "Bank APIs", value: "bank_api" },
            { label: "GST / Tax portals", value: "gst" },
            { label: "E-commerce platforms", value: "ecommerce" },
            { label: "Logistics partners", value: "logistics" },
          ],
        },
        {
          id: "data_migration",
          type: "select",
          label: "Historical data migration scope",
          required: true,
          options: [
            { label: "Full (last 5+ years)", value: "full" },
            { label: "Last 2-3 years", value: "partial" },
            { label: "Current year only", value: "current_year" },
            { label: "Master data only (no transactions)", value: "master_only" },
            { label: "Start fresh", value: "fresh" },
          ],
        },
        {
          id: "api_requirements",
          type: "multiselect",
          label: "External API integrations needed",
          options: [
            { label: "REST APIs for partners", value: "rest" },
            { label: "Webhooks", value: "webhooks" },
            { label: "EDI", value: "edi" },
            { label: "GSTN (India)", value: "gstn" },
            { label: "Banking APIs", value: "banking" },
            { label: "Aadhaar / e-KYC", value: "ekyc" },
            { label: "WhatsApp / SMS / Email", value: "comms" },
          ],
        },
      ],
    },
    {
      id: "erp-compliance",
      title: "Compliance & Security",
      questions: [
        {
          id: "compliance_required",
          type: "multiselect",
          label: "Compliance requirements",
          required: true,
          options: [
            { label: "GST (India)", value: "gst" },
            { label: "TDS / TCS", value: "tds" },
            { label: "Income Tax", value: "income_tax" },
            { label: "DPDP Act", value: "dpdp" },
            { label: "SOX (US listed)", value: "sox" },
            { label: "ISO 27001", value: "iso27001" },
            { label: "SOC 2", value: "soc2" },
            { label: "GDPR", value: "gdpr" },
            { label: "Industry-specific (e.g. FDA)", value: "industry" },
          ],
        },
        {
          id: "audit_trail",
          type: "boolean",
          label: "Require detailed audit trail for all transactions?",
          required: true,
        },
        {
          id: "rbac_complexity",
          type: "select",
          label: "Role-based access control complexity",
          required: true,
          options: [
            { label: "Simple (admin, manager, user)", value: "simple" },
            { label: "Department-based", value: "department" },
            { label: "Hierarchical (entity > dept > team > user)", value: "hierarchical" },
            { label: "Field-level permissions", value: "field_level" },
          ],
        },
        {
          id: "hosting_preference",
          type: "radio",
          label: "Hosting preference",
          required: true,
          options: [
            { label: "Cloud (AWS/GCP/Vercel)", value: "cloud" },
            { label: "On-premise", value: "onprem" },
            { label: "Hybrid", value: "hybrid" },
            { label: "MB Tech Labs managed", value: "managed" },
          ],
        },
      ],
    },
    {
      id: "erp-mobile",
      title: "Mobile & Reporting",
      questions: [
        {
          id: "mobile_app",
          type: "boolean",
          label: "Need mobile app (for approvals, dashboards, etc.)?",
        },
        {
          id: "mobile_features",
          type: "multiselect",
          label: "Mobile app features",
          showIf: [{ questionId: "mobile_app", op: "truthy", value: true }],
          options: [
            { label: "Approval workflows", value: "approvals" },
            { label: "Dashboard view", value: "dashboard" },
            { label: "Expense submission", value: "expense" },
            { label: "Inventory check", value: "inventory" },
            { label: "Sales order entry", value: "sales" },
            { label: "Push notifications", value: "push" },
            { label: "Offline mode", value: "offline" },
          ],
        },
        {
          id: "reporting_needs",
          type: "multiselect",
          label: "Reporting & analytics needs",
          required: true,
          options: [
            { label: "Standard financial reports", value: "financial" },
            { label: "Custom dashboards", value: "custom_dash" },
            { label: "Scheduled email reports", value: "scheduled" },
            { label: "Export to Excel/PDF", value: "export" },
            { label: "Drill-down analytics", value: "drill" },
            { label: "Predictive / AI", value: "ai" },
          ],
        },
      ],
    },
  ],
  uploadRequirements: [
    {
      category: "documents",
      label: "Process Flow Documents",
      required: true,
      description: "Current process flow diagrams for finance, inventory, HR, etc.",
      accept: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
      maxSizeMB: 50,
      multiple: true,
    },
    {
      category: "data",
      label: "Master Data Sample (chart of accounts, items, vendors)",
      required: true,
      accept: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel", "text/csv", "application/zip"],
      maxSizeMB: 25,
      multiple: true,
    },
    {
      category: "legal",
      label: "Company Registration / PAN / GST",
      required: true,
      accept: ["application/pdf"],
      maxSizeMB: 10,
      multiple: true,
    },
    {
      category: "branding",
      label: "Company Logo & Brand Guidelines",
      required: true,
      accept: ["image/png", "image/jpeg", "image/svg+xml", "application/zip"],
      maxSizeMB: 25,
    },
    {
      category: "reference",
      label: "Reference ERP Systems",
      description: "Screenshots of ERP UIs you like (SAP, Oracle, Zoho, etc.)",
      accept: ["image/png", "image/jpeg", "application/zip"],
      maxSizeMB: 25,
      multiple: true,
    },
  ],
  workflowRequirements: [
    {
      flow: "approval",
      label: "Procurement Approval",
      required: true,
      defaultStages: ["PR Raised", "Manager Approve", "Finance Approve", "PO Issue", "Goods Receipt", "Invoice Approve", "Payment"],
    },
    {
      flow: "verification",
      label: "Invoice Verification",
      required: true,
      defaultStages: ["Receive Invoice", "Match with PO", "Match with GRN", "Tax Validate", "Approve", "Post to GL"],
    },
    {
      flow: "payment",
      label: "Payment Run",
      required: true,
      defaultStages: ["Vendor Selection", "Approval", "Payment Release", "Bank File", "Reconcile"],
    },
    {
      flow: "reporting",
      label: "Financial Close",
      required: true,
      defaultStages: ["Sub-ledger Close", "Reclassifications", "Reconcile", "Review", "Publish", "Audit Trail"],
    },
    {
      flow: "customer",
      label: "Sales Order Flow",
      required: true,
      defaultStages: ["Quote", "Order", "Credit Check", "Allocate Stock", "Ship", "Invoice", "Collect"],
    },
    {
      flow: "staff",
      label: "Employee Onboarding",
      defaultStages: ["Offer", "Accept", "Document Verify", "Setup", "First Day", "Probation Review"],
    },
  ],
};
