/**
 * Jamaat / Community Template
 * ---------------------------
 * For religious communities, masjids, madrasas, and community organizations.
 * Focus: member management, events, donations, education, communications.
 */
import type { SrgTemplate } from "../types";

export const jamaatTemplate: SrgTemplate = {
  id: "jamaat",
  name: "Jamaat / Community",
  tagline: "Member management, events, donations & education",
  description:
    "For religious communities, masjids, madrasas, and faith-based organizations managing members, events, and community programs.",
  icon: "Users",
  accent: "from-cyan/20 to-cyan/5",
  suggestedGoals: [
    "Centralize member database across all units",
    "Launch event registration & RSVP system",
    "Track donations and zakat collection",
    "Digitize madrasa attendance and progress",
  ],
  sections: [
    {
      id: "jamaat-profile",
      title: "Community Profile",
      questions: [
        {
          id: "community_type",
          type: "select",
          label: "Community type",
          required: true,
          options: [
            { label: "Masjid / Mosque", value: "masjid" },
            { label: "Madrasa / School", value: "madrasa" },
            { label: "Jamaat (regional)", value: "jamaat_regional" },
            { label: "Tablighi Group", value: "tablighi" },
            { label: "Youth Wing", value: "youth" },
            { label: "Women's Wing", value: "womens" },
            { label: "Waqf Board", value: "waqf" },
            { label: "Other Faith Community", value: "other" },
          ],
        },
        {
          id: "member_count",
          type: "number",
          label: "Approximate community member count",
          required: true,
          min: 10,
          max: 1000000,
        },
        {
          id: "unit_count",
          type: "number",
          label: "Number of local units/branches",
          required: true,
          min: 1,
          max: 10000,
          help: "e.g. number of masjids, madrasa branches, local chapters",
        },
        {
          id: "hierarchy_levels",
          type: "select",
          label: "Organizational hierarchy",
          required: true,
          options: [
            { label: "Single unit (no hierarchy)", value: "single" },
            { label: "Two-level (center + units)", value: "two_level" },
            { label: "Three-level (national + state + local)", value: "three_level" },
            { label: "Multi-level (national + state + district + local)", value: "multi_level" },
          ],
        },
        {
          id: "languages",
          type: "multiselect",
          label: "Languages used in community communications",
          required: true,
          options: [
            { label: "Urdu", value: "ur" },
            { label: "Arabic", value: "ar" },
            { label: "Hindi", value: "hi" },
            { label: "English", value: "en" },
            { label: "Tamil", value: "ta" },
            { label: "Malayalam", value: "ml" },
            { label: "Bengali", value: "bn" },
            { label: "Gujarati", value: "gu" },
            { label: "Kannada", value: "kn" },
          ],
        },
      ],
    },
    {
      id: "jamaat-modules",
      title: "Required Modules",
      questions: [
        {
          id: "modules_needed",
          type: "multiselect",
          label: "Which modules do you need?",
          required: true,
          options: [
            { label: "Member Database", value: "members" },
            { label: "Family Tree Linking", value: "family_tree" },
            { label: "Event Management & RSVP", value: "events" },
            { label: "Donation / Zakat Collection", value: "donations" },
            { label: "Madrasa / Class Management", value: "madrasa" },
            { label: "Prayer Time Notifications", value: "prayer_times" },
            { label: "Announcements / Broadcast", value: "announcements" },
            { label: "Member Mobile App", value: "mobile_app" },
            { label: "Volunteer Management", value: "volunteers" },
            { label: "Funeral / Nikah Records", value: "records" },
            { label: "Qurbani / Sadaqah Tracking", value: "qurbani" },
            { label: "Library / Resource Center", value: "library" },
          ],
        },
        {
          id: "madrasa_features",
          type: "multiselect",
          label: "Madrasa / education features needed",
          showIf: [{ questionId: "modules_needed", op: "contains", value: "madrasa" }],
          options: [
            { label: "Student enrollment", value: "enrollment" },
            { label: "Attendance tracking", value: "attendance" },
            { label: "Grade / Hifz progress", value: "grades" },
            { label: "Teacher management", value: "teachers" },
            { label: "Parent portal", value: "parents" },
            { label: "Fee collection", value: "fees" },
            { label: "Exam scheduling", value: "exams" },
            { label: "Report cards", value: "report_cards" },
          ],
        },
        {
          id: "event_features",
          type: "multiselect",
          label: "Event management features",
          showIf: [{ questionId: "modules_needed", op: "contains", value: "events" }],
          options: [
            { label: "Event calendar", value: "calendar" },
            { label: "Online RSVP", value: "rsvp" },
            { label: "Ticket / paid events", value: "tickets" },
            { label: "Check-in / QR scan", value: "checkin" },
            { label: "Live streaming link", value: "livestream" },
            { label: "Post-event feedback", value: "feedback" },
          ],
        },
      ],
    },
    {
      id: "jamaat-donations",
      title: "Donations & Finance",
      questions: [
        {
          id: "donation_types",
          type: "multiselect",
          label: "Donation categories to track",
          options: [
            { label: "Zakat", value: "zakat" },
            { label: "Sadaqah", value: "sadaqah" },
            { label: "Fitrah", value: "fitrah" },
            { label: "Qurbani", value: "qurbani" },
            { label: "Masjid construction fund", value: "construction" },
            { label: "Madrasa fund", value: "madrasa_fund" },
            { label: "Relief / emergency", value: "relief" },
          ],
        },
        {
          id: "donation_receipts",
          type: "boolean",
          label: "Auto-generate donation receipts (80G/12A)?",
        },
        {
          id: "donation_channels",
          type: "multiselect",
          label: "Donation collection channels",
          required: true,
          options: [
            { label: "Cash box at masjid", value: "cash" },
            { label: "UPI QR", value: "upi" },
            { label: "Online portal", value: "online" },
            { label: "Bank transfer", value: "bank" },
            { label: "Cheque", value: "cheque" },
            { label: "Recurring auto-debit", value: "recurring" },
          ],
        },
      ],
    },
    {
      id: "jamaat-comms",
      title: "Communications & Notifications",
      questions: [
        {
          id: "comms_channels",
          type: "multiselect",
          label: "Communication channels to integrate",
          required: true,
          options: [
            { label: "SMS", value: "sms" },
            { label: "WhatsApp", value: "whatsapp" },
            { label: "Email", value: "email" },
            { label: "Push notifications (app)", value: "push" },
            { label: "Telegram", value: "telegram" },
            { label: "IVR / voice call", value: "ivr" },
          ],
        },
        {
          id: "broadcast_segments",
          type: "multiselect",
          label: "Broadcast audience segmentation",
          options: [
            { label: "All members", value: "all" },
            { label: "By geography", value: "geography" },
            { label: "By age group", value: "age" },
            { label: "By gender", value: "gender" },
            { label: "By role (teacher, imam, etc.)", value: "role" },
            { label: "By donation tier", value: "donor_tier" },
            { label: "By event attendance", value: "event_attendance" },
          ],
        },
        {
          id: "prayer_time_integration",
          type: "boolean",
          label: "Need prayer time integration (Adhan notifications)?",
        },
      ],
    },
  ],
  uploadRequirements: [
    {
      category: "legal",
      label: "Registration Certificate (Trust/Society)",
      required: true,
      accept: ["application/pdf"],
      maxSizeMB: 10,
    },
    {
      category: "branding",
      label: "Community Logo & Branding",
      required: true,
      accept: ["image/png", "image/jpeg", "image/svg+xml", "application/zip"],
      maxSizeMB: 25,
      multiple: true,
    },
    {
      category: "data",
      label: "Member Data Sample (anonymized)",
      description: "CSV/XLSX with sample member fields",
      accept: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/csv"],
      maxSizeMB: 10,
    },
    {
      category: "documents",
      label: "Organizational Hierarchy Chart",
      accept: ["application/pdf", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
      maxSizeMB: 15,
    },
    {
      category: "reference",
      label: "Reference Community Apps",
      description: "Screenshots of similar apps you like",
      accept: ["image/png", "image/jpeg", "application/zip"],
      maxSizeMB: 25,
      multiple: true,
    },
  ],
  workflowRequirements: [
    {
      flow: "customer",
      label: "Member Journey",
      required: true,
      defaultStages: ["Onboarding", "Profile Verification", "Family Link", "Unit Assignment", "Active Member"],
    },
    {
      flow: "approval",
      label: "Event Approval",
      required: true,
      defaultStages: ["Proposal", "Committee Review", "Budget Approve", "Schedule", "Publish"],
    },
    {
      flow: "payment",
      label: "Donation Processing",
      required: true,
      defaultStages: ["Donor Initiates", "Payment Gateway", "Receipt", "Fund Categorize", "Treasurer Review"],
    },
    {
      flow: "reporting",
      label: "Community Reports",
      required: true,
      defaultStages: ["Monthly Compile", "Committee Review", "Member Notice", "Annual Report"],
    },
    {
      flow: "staff",
      label: "Volunteer / Staff Workflow",
      defaultStages: ["Recruit", "Assign Role", "Task Allocation", "Report", "Recognize"],
    },
  ],
};
